version: "3"
services:
  db:
    image: postgres:13.3
    container_name: db
    environment:
      POSTGRES_DB: ${DEFAULT_DB_NAME:-appdb}
      POSTGRES_USER: ${DEFAULT_DB_USER:-dbuser}
      POSTGRES_PASSWORD: ${DEFAULT_DB_PASSWORD:-dbpass}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      PGTZ: Asia/Tokyo
      TZ: Asia/Tokyo
    ports:
      - "${LOCAL_DB_PORT:-5432}:${DEFAULT_DB_PORT:-5432}"
    volumes:
      - database:/var/lib/postgresql/data
      - ./createDDL.sql:/docker-entrypoint-initdb.d/createDDL.sql
volumes:
  database:
    driver: local
