---
apiVersion: v1
kind: Secret
metadata:
  name: lesson-k8s-secret
  namespace: default
stringData:
  dbhost: lesson-k8s-db
  dbname: appdb
  username: dbuser
  password: dbpass
type: Opaque
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/lib/minikube/pv01
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lesson-k8s
  name: postgresql-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lesson-k8s
  name: lesson-k8s-db
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 5432
  selector:
    app: lesson-k8s
    tier: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lesson-k8s
  name: lesson-k8s-db
  namespace: default
spec:
  selector:
    matchLabels:
      app: lesson-k8s
      tier: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lesson-k8s
        tier: postgresql
      namespace: default
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: lesson-k8s-secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: lesson-k8s-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: lesson-k8s-secret
            - name: POSTGRES_INITDB_ARGS
              value: --encoding=UTF-8 --locale=C
            - name: PGTZ
              value: Asia/Tokyo
            - name: TZ
              value: Asia/Tokyo
          image: postgres:13.3
          name: db
          ports:
            - containerPort: 5432
              name: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-persistent-storage
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgresql-pv-claim
