---
apiVersion: v1
kind: Secret
metadata:
  name: lesson-k8s-secret
  namespace: default
stringData:
  dbhost: lesson-k8s-db
  dbname: appdb
  username: dbuser
  password: dbpass
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: lesson-k8s-tls-secret
  namespace: default
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPekNDQWlPZ0F3SUJBZ0lKQUxKcWhLeTNZVkVITUEwR0NTcUdTSWIzRFFFQkJRVUFNRW94Q3pBSkJnTlYKQkFZVEFrcFFNUTR3REFZRFZRUUlEQVZEYUdsaVlURVJNQThHQTFVRUJ3d0lTV05vYVd0aGQyRXhHREFXQmdOVgpCQU1NRDJ4bGMzTnZiaTFyT0hNdWRHVnpkREFlRncweU1URXdNVEF3T1RNNU1qSmFGdzB5TkRBeE1UTXdPVE01Ck1qSmFNRW94Q3pBSkJnTlZCQVlUQWtwUU1RNHdEQVlEVlFRSURBVkRhR2xpWVRFUk1BOEdBMVVFQnd3SVNXTm8KYVd0aGQyRXhHREFXQmdOVkJBTU1EMnhsYzNOdmJpMXJPSE11ZEdWemREQ0NBU0l3RFFZSktvWklodmNOQVFFQgpCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOTU95bHU5eWhWcWdHWEhKWXE2OFZ6TGc1c09sMzNoUkxnMTJyZktzRzIvCnNPTFpzMWpTQUp6TDVXMzdrZXI0S0g3cmgzSVNwdUpnak91YW9JUTdxVUFnSzFESDI5aFdrNGJrQW16M0t5UWMKOHRhS0hLNGFFRVBBVXk0dURjcEpjUm43T0ZHeFVkbzZLWHlIR2Q4VjVBRFpXU3hWUlF0VW9mSVp2N1E2WTZIYwpaYXRQVVlOK25Iend0MG5tcmtUTEp0OGFFejVidGFUYVBEdUhlbEJkS05uYWFvWUNESGFWUzhZcWFtZzNVckpvClF2VHMyZmRMTFpnNzN0MHgwY3RuU0tmY1pERlozV2t2WHJJZlhROVhuMVV2ZHhwZUtqYTBJdTFqbmt6RUVyQ2UKejdJekNaeG05R2Nib0hZcnZmN2t1TC9YQmlGbFlxMmRZWDYzbDRzTmRCRUNBd0VBQWFNa01DSXdJQVlEVlIwUgpCQmt3RjRJUGJHVnpjMjl1TFdzNGN5NTBaWE4waHdUQXFFQUNNQTBHQ1NxR1NJYjNEUUVCQlFVQUE0SUJBUUJ5Ck1xMVpqZG8rREVQdVB6bjVVSEY0ZWNDVFNxNmFCcWIzS3VXZ2xjMzgyZVo1WEl5bEsvU29xSUF3anROR3hTRUYKVVRadDJ1cDBaS0Rvbm9RUng4L25CeVN1Ri9sMldNRWlvMWZDdzlHZHlIdjlTSHFaYTV6b0NjV015MG9lMXZSYQpxWXVDc3RuUENUY01xUXZWM2o5OFllYkwwclU3alJKaVVGdVZJNm1zUmZzejVKSk5uRzJTNHRQMVdtYXlhaEtuCnhZSFFmdVBnbFRVMkNzbVJROTdqdkpwbThmSERRMW11UWd0UmwxN3dnc1VGbVBvSExYNENDSE94di9jZmtkYSsKSzBVeitMZXkvbEZRdHlwODV6QXpKdjNuVWtQQVEvbTcrUWtiTUtkNGlqRmRuUmdYa0poUFIwa29TYkJHa1k2TQpPa3NEQzdWU0lXUVRlM3dWcEFtZAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMHc3S1c3M0tGV3FBWmNjbGlycnhYTXVEbXc2WGZlRkV1RFhhdDhxd2JiK3c0dG16CldOSUFuTXZsYmZ1UjZ2Z29mdXVIY2hLbTRtQ002NXFnaER1cFFDQXJVTWZiMkZhVGh1UUNiUGNySkJ6eTFvb2MKcmhvUVE4QlRMaTROeWtseEdmczRVYkZSMmpvcGZJY1ozeFhrQU5sWkxGVkZDMVNoOGhtL3REcGpvZHhscTA5UgpnMzZjZlBDM1NlYXVSTXNtM3hvVFBsdTFwTm84TzRkNlVGMG8yZHBxaGdJTWRwVkx4aXBxYURkU3NtaEM5T3paCjkwc3RtRHZlM1RIUnkyZElwOXhrTVZuZGFTOWVzaDlkRDFlZlZTOTNHbDRxTnJRaTdXT2VUTVFTc0o3UHNqTUoKbkdiMFp4dWdkaXU5L3VTNHY5Y0dJV1ZpcloxaGZyZVhpdzEwRVFJREFRQUJBb0lCQUdpWXVPSzBjUlVoL2RYeQoxd0VrMm44UmdQeDBROUdudFdYUmtyNXBIZnlWOW5UR1RTS2ttSmNjV1d5ak0xS09mNHMrOEpZdzlqSFVoYUl4CnRJRTBEQkh5bjJUZVYyNmtvV0pGVjRwbkNDTlNrV3FQY2QwNm4zcmtNcFQ5VCtwRGNXRGQ1ckJkdjJIMlZ4OFcKMlZSOHhjMUI2ZmFWbjYwWTJWVmhPMmQzVkc4Zkl0Qk5tRVd3S3lhRzhnK01UZHlzd2JNNS9oYmY5dnJEMkN0Kwo1UEU3M3lnT1R3bnBndmExcVExVTk3LytPaGZJVkJob1FwTnIzZ1FmTTZnY2V5Sm1yMy9YZXhiYXUrNzVBUEtSCllJUWhSSXM5U2xONkVEWXJOL0dGTExLeVVvckZKdzg2cVRqWG9BOVFMcE9nbi9ESHFhTTJ3N1FhM2NGblJOS3kKQ0FqZHNWMENnWUVBK3p2OFVDUnZLaU1nQUY0TWtyYUNhcHNIL2tZRGJGMkZGTlFLRnJZQ01mL0lONzBsZUsrMworS2cvOTZZeTM5aiswL2U2TFJNUHdoUGRuS3NUOTlkOFQzYko5a1NEQkJUY3ZSQ0ZraHZaSE5Va21ESkxxTzQ3CnlmZlduaGlXNHIzWWVFQUUyMSt3U1IwYW9MNHk4a2YwS05oQnZKSTNxRDJXYXB3WkFPYmtsRThDZ1lFQTF3KzAKUytLNzIvTFlDRVNIbUhCSnhkdkRNRFlkcFN0WVVLdjc2R0hqMlNFYnAvTDBoQkwzNTVzeFFua1R6MXhFQ01yOAptTk9RNTZhcFAvUnVUUm9qb1UrWlpNbUpmeHN6eWlmMGZZKy92R3ZOZ1RrRWZFQ2wwMnFPOGlpNVNjcnhCQ05TCnNjYXloQnVwNDBJWVA1ZkM5aHlZTEQwOWxvWm5jRUMzVlF4RWVaOENnWUVBMGJtNG5scGI1a3dlS2RCWkpKeHcKOEhkc3k4bzhqMWplZ0kybHdtRzhJV3NLQStYRkF5T0ZLM0dndktha0w1T2czdWdkSmdXVWtRb3VaTnUzdHB6UApMRExZMDlsTG1idWtyYnUrRlVOa0VocW9DdGxwcWFMK2pGSjFlZExER3BNcXd1K0dYbTlaNVI4RG5JNUtUMURiCnRNRWExMFVrYXpER2dVYS81SzNhd1NjQ2dZQllkQm9ZMkNHaUhtaWlSZVZyV2t2TmVFejRxRmxiRk0vWEpsV08KeDZ4YUl0Ym9KZkpSM0NkZ2VDRXprTzhINjVBRCtkRVkzbk9NQTYwN0k4SzJMWmtZQU5BN2R2VDVkV3ZBcXR4UgpSRzE5QnUzWVIyWkQ0S2NUcEpFMG9uRkxHNUF6dm4rRnBRN0piVU5idUZTVzIwbVJ4a01FZHcrOHVIMFUyMWxNClBxWnZTd0tCZ1FENWw3dStJOUsxRkNyM3BQRno4ZHZMbXhXdzg3eUdPblZRYmRTQlJVc3Myemo2eFhaSW9Qdm0KWTljZldndjA0M2Z0S1dNSDJhN2NZclJob3RFMmFnMU5adm9IeHJyOS9QZGhVVWlPcEFQbjEvN3lVdGFvbjFGbgpXMnViVURqaTJNdG92MnozUHRiZWtVMXA4ZjNESldvOTRuWUpLZjY0bHAzRGQ0SFdJNjVpSkE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
type: kubernetes.io/tls
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/lib/minikube/pv01
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lesson-k8s
  name: postgresql-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lesson-k8s
  name: lesson-k8s-db
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 5432
  selector:
    app: lesson-k8s
    tier: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lesson-k8s
  name: lesson-k8s-db
  namespace: default
spec:
  selector:
    matchLabels:
      app: lesson-k8s
      tier: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lesson-k8s
        tier: postgresql
      namespace: default
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: lesson-k8s-secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: lesson-k8s-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: lesson-k8s-secret
            - name: POSTGRES_INITDB_ARGS
              value: --encoding=UTF-8 --locale=C
            - name: PGTZ
              value: Asia/Tokyo
            - name: TZ
              value: Asia/Tokyo
          image: postgres:13.3
          name: db
          ports:
            - containerPort: 5432
              name: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-persistent-storage
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgresql-pv-claim
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: lesson-k8s
  name: lesson-k8s
  namespace: default
spec:
  tls:
    - hosts:
        - lesson-k8s.test
      secretName: lesson-k8s-tls-secret
  rules:
    - host: lesson-k8s.test
      http:
        paths:
          - backend:
              service:
                name: lesson-k8s
                port:
                  name: http
            path: /
            pathType: Prefix
